name = "cryptomind-worker"
main = "./src/worker/index.ts"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cryptomind-db"
database_id = "${DB_ID}"

[vars]
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_KEY = "${SUPABASE_KEY}"
ENVIRONMENT = "${ENVIRONMENT}"
