name = "cryptomind-worker"
main = "./src/worker/index.ts"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"

[vars]
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_KEY = "${SUPABASE_KEY}"
ENVIRONMENT = "${ENVIRONMENT}"
